version: '3.3'

services:
  test:
    build:
      context: ..
      dockerfile: docker/Dockerfile.test
    image: ${IMAGE:-pipdevs/test}
    command: ${TEST_CMD:-dotnet test test/test.csproj}
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://localhost:27017/test
      - MONGO_HOST=localhost
      - MONGO_PORT=27017
      - MONGO_DB=test

  mongo:
    image: mongo:latest