version: '3.3'

services:
  test:
    build:
      context: ..
      dockerfile: docker/Dockerfile.test
    image: ${IMAGE:-pipdevs/test}
    command: ${TEST_CMD:-dotnet test test/test.csproj}
    depends_on:
      - redis
      - fluentd
      - elasticsearch
      - prometheus
      - pushgateway
      - mongo
    environment:
      - MONGO_URI=mongodb://localhost:27017/test
      - MONGO_HOST=localhost
      - MONGO_PORT=27017
      - MONGO_DB=test

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  fluentd:
    image: fluent/fluentd
    container_name: fluent
    volumes:
     - ./logs:/fluentd/log
    ports:
     - "24224:24224"
     
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.3
    container_name: elasticsearch
    environment:
      #- cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms128m -Xmx128m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"

  pushgateway:
    image: prom/pushgateway:latest
    container_name: pushgateway
    ports:
      - "9091:9091"

  mongo:
    image: mongo:latest